### ISSUE TITLE
missing quaternion.py? 

### ISSUE THREAD

**Issue by Bingo-1996** [dragonlong/equi-pose#1]
Hello author, thank you for releasing the code, but there seems to be one missing file? quaternion.py?
In addition, will the training and testing details on the NOCS dataset be available?
Since this work is the first self-supervised method for category-level OPE problem,  the complete training and testing details will greatly contribute to the follow-up research!!!

**Comment by dragonlong** [comment]
Hi, 

Thanks for pointing out this! I have done a quick fix to this issue, which is caused file renaming: the `quaternion.py` is actually renamed to `rotations.py` during the code cleaning. 

As for the training details on NOCS datasets, the training is pretty much the same as 'ModelNet40_partial', you could check for  at this moment.  Also in the current release, I have attached our data loading scripts for the preprocessed NOCS dataset(we segment the object point clouds using GT masks, on both synthetic and real set). That should also be helpful to you.

Best,
Xiaolong

**Comment by Bingo-1996** [comment]
Thank you very much, I will try it!

**Comment by Bingo-1996** [comment]
sorry to disturb again, but I cannot find the file 'data/anchors/sphere12.ply'?

**Comment by dragonlong** [comment]
Hi, 

It sits in '/models/vgtk/data/anchors'. The code should find this file automatically I believe. 

Best,
Xiaolong

**Comment by Bingo-1996** [comment]
oh, that's my careless, thank you!
